create table "order"
(
    id          integer generated by default as identity,
    number      text                                not null,
    date        timestamp default CURRENT_TIMESTAMP not null,
    customer_id integer not null
        constraint order_customer_id_fk
            references customer (id),
    stock       integer   default 0                 not null
);

create unique index order_id_uindex
    on "order" (id);

create index order_number_index
    on "order" (number);

