create table customer
(
    id      integer generated by default as identity,
    name    text not null,
    email   text not null,
    address text not null
);

create unique index customer_id_uindex
    on customer (id);

create index customer_email_index
    on customer (email);

