create table product
(
    id          integer generated by default as identity,
    name        text              not null,
    description text,
    price       numeric default 0 not null,
    stock       integer default 0 not null
);

create unique index product_id_uindex
    on product (id);

create index product_id_index
    on product (id);

